version: 2

updates:
  # GHA
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    reviewers:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/gha"
    target-branch: "dev"

  # Coraza
  - package-ecosystem: "docker"
    directory: "/coraza/api"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    reviewers:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/coraza/api"
    target-branch: "dev"
  - package-ecosystem: "gomod"
    directory: "/coraza/api"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    assignees:
      - "TheophileDiot"
    reviewers:
      - "TheophileDiot"
    commit-message:
      prefix: "deps/coraza/api"
    target-branch: "dev"
