# ⚠️ DO NOT USE THIS FILE, IT IS ONLY USED FOR INTERNAL TESTS ⚠️
# SEE README.md for instructions

version: '3.5'

services:
  bunkerweb:
    # image: bunkerity/bunkerweb:1.5.0
    build:
      context: /home/theophile/dev/bunkerweb-staging
      dockerfile: src/bw/Dockerfile
    ports:
      - 80:8080
      - 443:8443
    labels:
      - "bunkerweb.INSTANCE"
    environment:
      - SERVER_NAME=www.example.com
      - API_WHITELIST_IP=127.0.0.0/8 10.20.30.0/24
      - USE_VIRUSTOTAL=yes
      - VIRUSTOTAL_API=http://virustotal-api:8000
      - LOG_LEVEL=info
      - USE_BAD_BEHAVIOR=no
      - USE_BUNKERNET=no
      - USE_BLACKLIST=no
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_HOST=http://hello
      - REVERSE_PROXY_URL=/
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    # image: bunkerity/bunkerweb-scheduler:1.5.0
    build:
      context: /home/theophile/dev/bunkerweb-staging
      dockerfile: src/scheduler/Dockerfile
    depends_on:
      - bunkerweb
      - bw-docker
    volumes:
      - /tmp/bw-data:/data
    environment:
      - DOCKER_HOST=tcp://bw-docker:2375
    networks:
      - bw-universe
      - bw-docker

  bw-docker:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
    networks:
      - bw-docker

  virustotal-api:
    build: api
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - API_KEY=91980f5c26b326062228583effa8ddc8b6a5a275b3fe6ce8b80dd6cf775e62f0
    networks:
      - bw-universe

  hello:
    image: tutum/hello-world
    networks:
      - bw-services

volumes:
  bw-data:


networks:
  bw-services:
  bw-docker:
  bw-universe:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
