name: Tests

on:
  push:
    branches: [dev, main]

jobs:
  setup:
    runs-on: self-hosted
    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Get BW tag
        run: |
          if [ "$GITHUB_REF" = "refs/heads/main" ] ; then
            echo "BW_TAG=latest" >> $GITHUB_ENV
          else
            echo "BW_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull images
        run: ./tests/pull.sh

      - name: Run ClamAV tests
        run: ./tests/clamav.sh

      - name: Run CrowdSec tests
        run: ./tests/crowdsec.sh

      - name: Run VirusTotal tests
        run: ./tests
        env:
          VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}